#!/bin/sh
#
# MDEV configuration for OTA USB auto-update
# Also handles general USB hotplug
#
# Format: <deviceRegex> <UID>:<GID> <octalPermissions> [=|>path] [@|$|*<command>]
#
sd[a-z][0-9]*    0:0 660 */bin/ota_usb_hotplug
sd[a-z]*         0:0 660
mmcblk[0-9]p*    0:0 660
